all: paper

paper:
	pdflatex paper
	bibtex paper
	bibtex paper
	pdflatex paper


clean:
	rm -rf paper.log
	rm -rf paper.aux
	rm -rf paper.pdf
	rm -rf paper.lot
	rm -rf paper.aux
	rm -rf paper.dvi
	rm -rf paper.blg
	rm -rf paper.bbl
	rm -rf paper.ps
	rm -rf paperNotes.bib
	rm -rf texput.log

